AWSTemplateFormatVersion: 2010-09-09
Description: 'API Gateway Logging Role'

Resources:
  ApiGatewayLoggingRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ApiGatewayWebSocketLoggingRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs'
      Policies:
        - PolicyName: ApiGatewayLoggingPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:DescribeLogGroups'
                  - 'logs:DescribeLogStreams'
                  - 'logs:PutLogEvents'
                  - 'logs:GetLogEvents'
                  - 'logs:FilterLogEvents'
                Resource:
                  - 'arn:aws:logs:*:*:*'

Outputs:
  RoleArn:
    Description: 'ARN of the API Gateway Logging Role'
    Value: !GetAtt ApiGatewayLoggingRole.Arn
